[CmdletBinding()]
param(
    [ValidatePattern('^[A-Za-z0-9._-]+$')]
    [string]$Symbol = "XAUUSD",

    [ValidateSet("M1", "M5", "M15", "M30", "H1", "H4", "D1")]
    [string]$Period = "M15",

    [ValidatePattern('^[A-Za-z0-9._-]+\.set$')]
    [string]$PresetName = "RSIFibRetracementEA_demo.set",

    [ValidatePattern('^\d{4}\.\d{2}\.\d{2}$')]
    [string]$FromDate = "2026.07.01",

    [ValidatePattern('^\d{4}\.\d{2}\.\d{2}$')]
    [string]$ToDate = "2026.08.01",

    [ValidateRange(1.0, 1000000000.0)]
    [double]$Deposit = 3000.0,

    [ValidateRange(1, 5000)]
    [int]$Leverage = 100,

    [ValidatePattern('^[A-Za-z0-9._-]*$')]
    [string]$ReportName = "",

    [string]$InstallRoot = "C:\Program Files\MetaTrader 5",

    [ValidateRange(30, 3600)]
    [int]$TimeoutSeconds = 900,

    [ValidateRange(0.0, 100.0)]
    [double]$MinRealTicksPct = 99.0,

    [switch]$CloseRunningTerminal
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$from = [datetime]::ParseExact($FromDate, "yyyy.MM.dd", [Globalization.CultureInfo]::InvariantCulture)
$to = [datetime]::ParseExact($ToDate, "yyyy.MM.dd", [Globalization.CultureInfo]::InvariantCulture)
if ($to -le $from) {
    throw "ToDate must be later than FromDate."
}

if ([string]::IsNullOrWhiteSpace($ReportName)) {
    $presetTag = [IO.Path]::GetFileNameWithoutExtension($PresetName)
    $ReportName = "RSIFibEA_{0}_{1}_{2}_{3}_{4}" -f `
                  $Symbol, $Period, $presetTag,
                  $FromDate.Replace(".", ""), $ToDate.Replace(".", "")
}

$terminal = Join-Path $InstallRoot "terminal64.exe"
if (-not (Test-Path -LiteralPath $terminal -PathType Leaf)) {
    throw "MT5 terminal not found: $terminal"
}

$terminalRoot = Join-Path $env:APPDATA "MetaQuotes\Terminal"
$expectedOrigin = [IO.Path]::GetFullPath($InstallRoot).TrimEnd('\')
$dataDirectory = $null
foreach ($candidate in Get-ChildItem -LiteralPath $terminalRoot -Directory -ErrorAction Stop) {
    $originFile = Join-Path $candidate.FullName "origin.txt"
    if (-not (Test-Path -LiteralPath $originFile -PathType Leaf)) {
        continue
    }

    $candidateOrigin = (Get-Content -LiteralPath $originFile -Raw).Trim()
    if ($candidateOrigin -and
        [IO.Path]::GetFullPath($candidateOrigin).TrimEnd('\') -ieq $expectedOrigin) {
        $dataDirectory = $candidate.FullName
        break
    }
}
if (-not $dataDirectory) {
    throw "No MT5 data directory mapped to '$InstallRoot' was found."
}

$compiledExpert = Join-Path $dataDirectory "MQL5\Experts\RSIFibEA\RSIFibRetracementEA.ex5"
$preset = Join-Path (Join-Path $dataDirectory "MQL5\Profiles\Tester") $PresetName
if (-not (Test-Path -LiteralPath $compiledExpert -PathType Leaf)) {
    throw "Compiled EA missing. Run deploy_compile_mt5.ps1 first: $compiledExpert"
}
if (-not (Test-Path -LiteralPath $preset -PathType Leaf)) {
    throw "Tester preset missing. Run deploy_compile_mt5.ps1 first: $preset"
}

$running = @(Get-Process -Name "terminal64" -ErrorAction SilentlyContinue)
if ($running.Count -gt 0 -and -not $CloseRunningTerminal) {
    throw "MT5 is already running. Close it first or pass -CloseRunningTerminal."
}
if ($running.Count -gt 0) {
    foreach ($item in $running) {
        [void]$item.CloseMainWindow()
    }
    $closeDeadline = (Get-Date).AddSeconds(20)
    do {
        Start-Sleep -Milliseconds 500
        $running = @(Get-Process -Name "terminal64" -ErrorAction SilentlyContinue)
    } while ($running.Count -gt 0 -and (Get-Date) -lt $closeDeadline)

    if ($running.Count -gt 0) {
        throw "MT5 did not close gracefully; no forced termination was attempted."
    }
}

$runtimeDirectory = Join-Path $env:LOCALAPPDATA "RSIFibEA"
New-Item -ItemType Directory -Path $runtimeDirectory -Force | Out-Null
$configPath = Join-Path $runtimeDirectory ($ReportName + ".ini")
$reportPath = Join-Path $dataDirectory ($ReportName + ".htm")
$previousReportWriteUtc = [datetime]::MinValue
if (Test-Path -LiteralPath $reportPath -PathType Leaf) {
    $previousReportWriteUtc = (Get-Item -LiteralPath $reportPath).LastWriteTimeUtc
}

$depositText = $Deposit.ToString("0.00", [Globalization.CultureInfo]::InvariantCulture)
$configuration = @"
; Generated by run_mt5_backtest.ps1. Contains no account credentials.
[Experts]
Enabled=0
AllowLiveTrading=0
AllowDllImport=0

[Tester]
Expert=RSIFibEA\RSIFibRetracementEA
ExpertParameters=$PresetName
Symbol=$Symbol
Period=$Period
Deposit=$depositText
Currency=USD
Leverage=1:$Leverage
Model=4
ExecutionMode=0
Optimization=0
OptimizationCriterion=6
FromDate=$FromDate
ToDate=$ToDate
ForwardMode=0
Report=$ReportName
ReplaceReport=1
ShutdownTerminal=1
UseLocal=1
UseRemote=0
UseCloud=0
Visual=0
"@
[IO.File]::WriteAllText($configPath, $configuration, (New-Object Text.UTF8Encoding($false)))

$process = Start-Process -FilePath $terminal `
                         -ArgumentList ("/config:" + $configPath) `
                         -PassThru
if (-not $process.WaitForExit($TimeoutSeconds * 1000)) {
    throw "MT5 backtest exceeded $TimeoutSeconds seconds; no forced termination was attempted."
}
if ($process.ExitCode -ne 0) {
    throw "MT5 exited with code $($process.ExitCode)."
}
if (-not (Test-Path -LiteralPath $reportPath -PathType Leaf) -or
    (Get-Item -LiteralPath $reportPath).LastWriteTimeUtc -le $previousReportWriteUtc) {
    throw "MT5 did not create or refresh the expected report: $reportPath"
}

# Model=4 requests real ticks, but MT5 can silently synthesize history when
# the broker has no real-tick coverage for the requested window. Reject that
# report here instead of allowing an attractive but invalid result downstream.
$reader = New-Object IO.StreamReader($reportPath, $true)
try {
    $reportText = $reader.ReadToEnd()
}
finally {
    $reader.Dispose()
}
$qualityMatch = [regex]::Match(
    $reportText,
    '(?i)([-+]?\d+(?:[\.,]\d+)?)\s*%\s*(?:ticks?[^<]{0,12}|real\s+ticks?)'
)
if (-not $qualityMatch.Success) {
    throw "MT5 report does not expose a parseable real-tick percentage: $reportPath"
}
$realTicksText = $qualityMatch.Groups[1].Value.Replace(',', '.')
$realTicksPct = [double]::Parse(
    $realTicksText,
    [Globalization.CultureInfo]::InvariantCulture
)
if ($realTicksPct -lt $MinRealTicksPct) {
    throw "MT5 report real-tick quality is $realTicksPct%, required >= $MinRealTicksPct%: $reportPath"
}

[pscustomobject]@{
    Symbol = $Symbol
    Period = $Period
    Preset = $PresetName
    Window = "$FromDate -> $ToDate"
    Deposit = "$depositText USD"
    Leverage = "1:$Leverage"
    Model = "Every tick based on real ticks"
    RealTicksPct = $realTicksPct
    Config = $configPath
    Report = $reportPath
    ExitCode = $process.ExitCode
}
